# Generated by Django 4.0.3 on 2022-03-16 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0003_order_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='destination',
            field=models.CharField(max_length=255),
        ),
    ]
