# Generated by Django 4.0.2 on 2022-03-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0005_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
