# Generated by Django 4.0.2 on 2022-03-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleapp', '0006_alter_category_options_alter_product_options_and_more'),
        ('saleapp', '0006_alter_product_options_alter_product_unique_together'),
        ('saleapp', '0007_hashtag'),
    ]

    operations = [
    ]
